[package]
name = "kindle_rust"
version = "0.1.0"
authors = ["garyemerson <gmohammadioun@gmail.com>"]

[profile.release]
# lto = true
codegen-units = 1
incremental = false

[dependencies]
memmap = "0.6.2"
libc = "0.2.43"
image = "0.19.0"
chrono = "0.4.6"
